# Site Settings
title: C.V.
url: "http://www.bruno3s.com"
baseurl: "" #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar
repository: bruno3s/bru1987
permalink: pretty

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Bruno Silva
tagline: Electrical Engineer and IB Mathematics teacher
pic: bruno.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I'm Bruno, a 33 year-old Engineer and IB Mathematics teacher. I believe that, when teaching, one should meet students where they are, while incentivizing productive struggle (using open ended questions and projects is valuable here) in order to develop communication, inquirer capabilities and problem solving skills. Encouraging students to take risks and learn from their mistakes will make them lifelong learners.

#sidebar links
email: bru1987@gmail.com
#phone: 11 97558 5540
website: www.bruno3s.com #do not add http://
linkedin: bruno3s
github: bru1987
#twitter: '@bruno.3s'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
